package com.ocko.aventador.dao.model.aventador;

import java.time.LocalDateTime;
import java.math.BigDecimal;

public class InfiniteAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.account_id
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.member_id
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.account_alias
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private String accountAlias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.account_order
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private Integer accountOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.registered_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private LocalDateTime registeredDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.is_deleted
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.seed
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private BigDecimal seed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.fees_per
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private BigDecimal feesPer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.updated_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private LocalDateTime updatedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.kskyj_seed
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private BigDecimal kskyjSeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_account.kskyj_update_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	private LocalDateTime kskyjUpdateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.account_id
	 * @return  the value of aventador.infinite_account.account_id
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.account_id
	 * @param accountId  the value for aventador.infinite_account.account_id
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.member_id
	 * @return  the value of aventador.infinite_account.member_id
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.member_id
	 * @param memberId  the value for aventador.infinite_account.member_id
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.account_alias
	 * @return  the value of aventador.infinite_account.account_alias
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public String getAccountAlias() {
		return accountAlias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.account_alias
	 * @param accountAlias  the value for aventador.infinite_account.account_alias
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setAccountAlias(String accountAlias) {
		this.accountAlias = accountAlias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.account_order
	 * @return  the value of aventador.infinite_account.account_order
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public Integer getAccountOrder() {
		return accountOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.account_order
	 * @param accountOrder  the value for aventador.infinite_account.account_order
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setAccountOrder(Integer accountOrder) {
		this.accountOrder = accountOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.registered_date
	 * @return  the value of aventador.infinite_account.registered_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public LocalDateTime getRegisteredDate() {
		return registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.registered_date
	 * @param registeredDate  the value for aventador.infinite_account.registered_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setRegisteredDate(LocalDateTime registeredDate) {
		this.registeredDate = registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.is_deleted
	 * @return  the value of aventador.infinite_account.is_deleted
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.is_deleted
	 * @param isDeleted  the value for aventador.infinite_account.is_deleted
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.seed
	 * @return  the value of aventador.infinite_account.seed
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public BigDecimal getSeed() {
		return seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.seed
	 * @param seed  the value for aventador.infinite_account.seed
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setSeed(BigDecimal seed) {
		this.seed = seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.fees_per
	 * @return  the value of aventador.infinite_account.fees_per
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public BigDecimal getFeesPer() {
		return feesPer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.fees_per
	 * @param feesPer  the value for aventador.infinite_account.fees_per
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setFeesPer(BigDecimal feesPer) {
		this.feesPer = feesPer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.updated_date
	 * @return  the value of aventador.infinite_account.updated_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public LocalDateTime getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.updated_date
	 * @param updatedDate  the value for aventador.infinite_account.updated_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setUpdatedDate(LocalDateTime updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.kskyj_seed
	 * @return  the value of aventador.infinite_account.kskyj_seed
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public BigDecimal getKskyjSeed() {
		return kskyjSeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.kskyj_seed
	 * @param kskyjSeed  the value for aventador.infinite_account.kskyj_seed
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setKskyjSeed(BigDecimal kskyjSeed) {
		this.kskyjSeed = kskyjSeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_account.kskyj_update_date
	 * @return  the value of aventador.infinite_account.kskyj_update_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public LocalDateTime getKskyjUpdateDate() {
		return kskyjUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_account.kskyj_update_date
	 * @param kskyjUpdateDate  the value for aventador.infinite_account.kskyj_update_date
	 * @mbg.generated  Thu Jan 27 18:01:57 KST 2022
	 */
	public void setKskyjUpdateDate(LocalDateTime kskyjUpdateDate) {
		this.kskyjUpdateDate = kskyjUpdateDate;
	}
}