package com.ocko.aventador.dao.model.aventador;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.math.BigDecimal;

public class InfiniteStock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.infinite_id
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private Integer infiniteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.account_id
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.symbol
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.seed
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private BigDecimal seed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.infinite_type
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private String infiniteType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.started_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private LocalDate startedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.infinite_state
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private String infiniteState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.registered_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private LocalDateTime registeredDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.is_deleted
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.infinite_version
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private String infiniteVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.done_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private LocalDate doneDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.kskyj_seed
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private BigDecimal kskyjSeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.kskyj_average_price
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private BigDecimal kskyjAveragePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.kskyj_buy_price
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private BigDecimal kskyjBuyPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.kskyj_holding_quantity
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private Integer kskyjHoldingQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.kskyj_update_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private LocalDateTime kskyjUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.is_kskyj
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private Boolean isKskyj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.is_auto_trade
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	private Boolean isAutoTrade;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.infinite_id
	 * @return  the value of aventador.infinite_stock.infinite_id
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public Integer getInfiniteId() {
		return infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.infinite_id
	 * @param infiniteId  the value for aventador.infinite_stock.infinite_id
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setInfiniteId(Integer infiniteId) {
		this.infiniteId = infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.account_id
	 * @return  the value of aventador.infinite_stock.account_id
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.account_id
	 * @param accountId  the value for aventador.infinite_stock.account_id
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.symbol
	 * @return  the value of aventador.infinite_stock.symbol
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.symbol
	 * @param symbol  the value for aventador.infinite_stock.symbol
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.seed
	 * @return  the value of aventador.infinite_stock.seed
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public BigDecimal getSeed() {
		return seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.seed
	 * @param seed  the value for aventador.infinite_stock.seed
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setSeed(BigDecimal seed) {
		this.seed = seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.infinite_type
	 * @return  the value of aventador.infinite_stock.infinite_type
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public String getInfiniteType() {
		return infiniteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.infinite_type
	 * @param infiniteType  the value for aventador.infinite_stock.infinite_type
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setInfiniteType(String infiniteType) {
		this.infiniteType = infiniteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.started_date
	 * @return  the value of aventador.infinite_stock.started_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public LocalDate getStartedDate() {
		return startedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.started_date
	 * @param startedDate  the value for aventador.infinite_stock.started_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setStartedDate(LocalDate startedDate) {
		this.startedDate = startedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.infinite_state
	 * @return  the value of aventador.infinite_stock.infinite_state
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public String getInfiniteState() {
		return infiniteState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.infinite_state
	 * @param infiniteState  the value for aventador.infinite_stock.infinite_state
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setInfiniteState(String infiniteState) {
		this.infiniteState = infiniteState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.registered_date
	 * @return  the value of aventador.infinite_stock.registered_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public LocalDateTime getRegisteredDate() {
		return registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.registered_date
	 * @param registeredDate  the value for aventador.infinite_stock.registered_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setRegisteredDate(LocalDateTime registeredDate) {
		this.registeredDate = registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.is_deleted
	 * @return  the value of aventador.infinite_stock.is_deleted
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.is_deleted
	 * @param isDeleted  the value for aventador.infinite_stock.is_deleted
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.infinite_version
	 * @return  the value of aventador.infinite_stock.infinite_version
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public String getInfiniteVersion() {
		return infiniteVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.infinite_version
	 * @param infiniteVersion  the value for aventador.infinite_stock.infinite_version
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setInfiniteVersion(String infiniteVersion) {
		this.infiniteVersion = infiniteVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.done_date
	 * @return  the value of aventador.infinite_stock.done_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public LocalDate getDoneDate() {
		return doneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.done_date
	 * @param doneDate  the value for aventador.infinite_stock.done_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setDoneDate(LocalDate doneDate) {
		this.doneDate = doneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.kskyj_seed
	 * @return  the value of aventador.infinite_stock.kskyj_seed
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public BigDecimal getKskyjSeed() {
		return kskyjSeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.kskyj_seed
	 * @param kskyjSeed  the value for aventador.infinite_stock.kskyj_seed
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setKskyjSeed(BigDecimal kskyjSeed) {
		this.kskyjSeed = kskyjSeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.kskyj_average_price
	 * @return  the value of aventador.infinite_stock.kskyj_average_price
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public BigDecimal getKskyjAveragePrice() {
		return kskyjAveragePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.kskyj_average_price
	 * @param kskyjAveragePrice  the value for aventador.infinite_stock.kskyj_average_price
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setKskyjAveragePrice(BigDecimal kskyjAveragePrice) {
		this.kskyjAveragePrice = kskyjAveragePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.kskyj_buy_price
	 * @return  the value of aventador.infinite_stock.kskyj_buy_price
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public BigDecimal getKskyjBuyPrice() {
		return kskyjBuyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.kskyj_buy_price
	 * @param kskyjBuyPrice  the value for aventador.infinite_stock.kskyj_buy_price
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setKskyjBuyPrice(BigDecimal kskyjBuyPrice) {
		this.kskyjBuyPrice = kskyjBuyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.kskyj_holding_quantity
	 * @return  the value of aventador.infinite_stock.kskyj_holding_quantity
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public Integer getKskyjHoldingQuantity() {
		return kskyjHoldingQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.kskyj_holding_quantity
	 * @param kskyjHoldingQuantity  the value for aventador.infinite_stock.kskyj_holding_quantity
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setKskyjHoldingQuantity(Integer kskyjHoldingQuantity) {
		this.kskyjHoldingQuantity = kskyjHoldingQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.kskyj_update_date
	 * @return  the value of aventador.infinite_stock.kskyj_update_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public LocalDateTime getKskyjUpdateDate() {
		return kskyjUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.kskyj_update_date
	 * @param kskyjUpdateDate  the value for aventador.infinite_stock.kskyj_update_date
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setKskyjUpdateDate(LocalDateTime kskyjUpdateDate) {
		this.kskyjUpdateDate = kskyjUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.is_kskyj
	 * @return  the value of aventador.infinite_stock.is_kskyj
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public Boolean getIsKskyj() {
		return isKskyj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.is_kskyj
	 * @param isKskyj  the value for aventador.infinite_stock.is_kskyj
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setIsKskyj(Boolean isKskyj) {
		this.isKskyj = isKskyj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.is_auto_trade
	 * @return  the value of aventador.infinite_stock.is_auto_trade
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public Boolean getIsAutoTrade() {
		return isAutoTrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.is_auto_trade
	 * @param isAutoTrade  the value for aventador.infinite_stock.is_auto_trade
	 * @mbg.generated  Tue Mar 22 20:08:04 KST 2022
	 */
	public void setIsAutoTrade(Boolean isAutoTrade) {
		this.isAutoTrade = isAutoTrade;
	}
}