package com.ocko.aventador.dao.model.aventador;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.math.BigDecimal;

public class InfiniteStock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.infinite_id
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private Integer infiniteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.account_id
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.symbol
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.seed
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private BigDecimal seed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.infinite_type
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private String infiniteType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.started_date
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private LocalDate startedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.infinite_state
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private String infiniteState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.registered_date
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private LocalDateTime registeredDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_stock.is_deleted
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	private Boolean isDeleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.infinite_id
	 * @return  the value of aventador.infinite_stock.infinite_id
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public Integer getInfiniteId() {
		return infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.infinite_id
	 * @param infiniteId  the value for aventador.infinite_stock.infinite_id
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setInfiniteId(Integer infiniteId) {
		this.infiniteId = infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.account_id
	 * @return  the value of aventador.infinite_stock.account_id
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.account_id
	 * @param accountId  the value for aventador.infinite_stock.account_id
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.symbol
	 * @return  the value of aventador.infinite_stock.symbol
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.symbol
	 * @param symbol  the value for aventador.infinite_stock.symbol
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.seed
	 * @return  the value of aventador.infinite_stock.seed
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public BigDecimal getSeed() {
		return seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.seed
	 * @param seed  the value for aventador.infinite_stock.seed
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setSeed(BigDecimal seed) {
		this.seed = seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.infinite_type
	 * @return  the value of aventador.infinite_stock.infinite_type
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public String getInfiniteType() {
		return infiniteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.infinite_type
	 * @param infiniteType  the value for aventador.infinite_stock.infinite_type
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setInfiniteType(String infiniteType) {
		this.infiniteType = infiniteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.started_date
	 * @return  the value of aventador.infinite_stock.started_date
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public LocalDate getStartedDate() {
		return startedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.started_date
	 * @param startedDate  the value for aventador.infinite_stock.started_date
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setStartedDate(LocalDate startedDate) {
		this.startedDate = startedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.infinite_state
	 * @return  the value of aventador.infinite_stock.infinite_state
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public String getInfiniteState() {
		return infiniteState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.infinite_state
	 * @param infiniteState  the value for aventador.infinite_stock.infinite_state
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setInfiniteState(String infiniteState) {
		this.infiniteState = infiniteState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.registered_date
	 * @return  the value of aventador.infinite_stock.registered_date
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public LocalDateTime getRegisteredDate() {
		return registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.registered_date
	 * @param registeredDate  the value for aventador.infinite_stock.registered_date
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setRegisteredDate(LocalDateTime registeredDate) {
		this.registeredDate = registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_stock.is_deleted
	 * @return  the value of aventador.infinite_stock.is_deleted
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_stock.is_deleted
	 * @param isDeleted  the value for aventador.infinite_stock.is_deleted
	 * @mbg.generated  Fri Dec 03 16:33:09 KST 2021
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
}