package com.ocko.aventador.dao.model.aventador;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.math.BigDecimal;

public class InfiniteHistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.infinite_history_id
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private Integer infiniteHistoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.infinite_id
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private Integer infiniteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.trade_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private LocalDate tradeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.trade_type
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private String tradeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.unit_price
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private BigDecimal unitPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.quantity
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.registered_type
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private String registeredType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.registered_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private LocalDateTime registeredDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.updated_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private LocalDateTime updatedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.infinite_history.is_deleted
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	private Boolean isDeleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.infinite_history_id
	 * @return  the value of aventador.infinite_history.infinite_history_id
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public Integer getInfiniteHistoryId() {
		return infiniteHistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.infinite_history_id
	 * @param infiniteHistoryId  the value for aventador.infinite_history.infinite_history_id
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setInfiniteHistoryId(Integer infiniteHistoryId) {
		this.infiniteHistoryId = infiniteHistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.infinite_id
	 * @return  the value of aventador.infinite_history.infinite_id
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public Integer getInfiniteId() {
		return infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.infinite_id
	 * @param infiniteId  the value for aventador.infinite_history.infinite_id
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setInfiniteId(Integer infiniteId) {
		this.infiniteId = infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.trade_date
	 * @return  the value of aventador.infinite_history.trade_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public LocalDate getTradeDate() {
		return tradeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.trade_date
	 * @param tradeDate  the value for aventador.infinite_history.trade_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setTradeDate(LocalDate tradeDate) {
		this.tradeDate = tradeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.trade_type
	 * @return  the value of aventador.infinite_history.trade_type
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public String getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.trade_type
	 * @param tradeType  the value for aventador.infinite_history.trade_type
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.unit_price
	 * @return  the value of aventador.infinite_history.unit_price
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public BigDecimal getUnitPrice() {
		return unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.unit_price
	 * @param unitPrice  the value for aventador.infinite_history.unit_price
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.quantity
	 * @return  the value of aventador.infinite_history.quantity
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.quantity
	 * @param quantity  the value for aventador.infinite_history.quantity
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.registered_type
	 * @return  the value of aventador.infinite_history.registered_type
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public String getRegisteredType() {
		return registeredType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.registered_type
	 * @param registeredType  the value for aventador.infinite_history.registered_type
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setRegisteredType(String registeredType) {
		this.registeredType = registeredType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.registered_date
	 * @return  the value of aventador.infinite_history.registered_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public LocalDateTime getRegisteredDate() {
		return registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.registered_date
	 * @param registeredDate  the value for aventador.infinite_history.registered_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setRegisteredDate(LocalDateTime registeredDate) {
		this.registeredDate = registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.updated_date
	 * @return  the value of aventador.infinite_history.updated_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public LocalDateTime getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.updated_date
	 * @param updatedDate  the value for aventador.infinite_history.updated_date
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setUpdatedDate(LocalDateTime updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.infinite_history.is_deleted
	 * @return  the value of aventador.infinite_history.is_deleted
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.infinite_history.is_deleted
	 * @param isDeleted  the value for aventador.infinite_history.is_deleted
	 * @mbg.generated  Wed Dec 15 11:15:50 KST 2021
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
}