package com.ocko.aventador.dao.model.aventador;

import java.util.Date;
import java.time.LocalDateTime;

public class MemberAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.member_id
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.member_email
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private String memberEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.member_name
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private String memberName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.member_password
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private String memberPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.member_status
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private String memberStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.member_roles
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private String memberRoles;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.subscription_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private LocalDateTime subscriptionDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.unsubscription_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private LocalDateTime unsubscriptionDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.password_expiration_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private LocalDateTime passwordExpirationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_account.etc_info
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	private String etcInfo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.member_id
	 * @return  the value of aventador.member_account.member_id
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.member_id
	 * @param memberId  the value for aventador.member_account.member_id
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.member_email
	 * @return  the value of aventador.member_account.member_email
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public String getMemberEmail() {
		return memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.member_email
	 * @param memberEmail  the value for aventador.member_account.member_email
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setMemberEmail(String memberEmail) {
		this.memberEmail = memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.member_name
	 * @return  the value of aventador.member_account.member_name
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public String getMemberName() {
		return memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.member_name
	 * @param memberName  the value for aventador.member_account.member_name
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.member_password
	 * @return  the value of aventador.member_account.member_password
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public String getMemberPassword() {
		return memberPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.member_password
	 * @param memberPassword  the value for aventador.member_account.member_password
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setMemberPassword(String memberPassword) {
		this.memberPassword = memberPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.member_status
	 * @return  the value of aventador.member_account.member_status
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public String getMemberStatus() {
		return memberStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.member_status
	 * @param memberStatus  the value for aventador.member_account.member_status
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setMemberStatus(String memberStatus) {
		this.memberStatus = memberStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.member_roles
	 * @return  the value of aventador.member_account.member_roles
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public String getMemberRoles() {
		return memberRoles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.member_roles
	 * @param memberRoles  the value for aventador.member_account.member_roles
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setMemberRoles(String memberRoles) {
		this.memberRoles = memberRoles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.subscription_date
	 * @return  the value of aventador.member_account.subscription_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public LocalDateTime getSubscriptionDate() {
		return subscriptionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.subscription_date
	 * @param subscriptionDate  the value for aventador.member_account.subscription_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setSubscriptionDate(LocalDateTime subscriptionDate) {
		this.subscriptionDate = subscriptionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.unsubscription_date
	 * @return  the value of aventador.member_account.unsubscription_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public LocalDateTime getUnsubscriptionDate() {
		return unsubscriptionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.unsubscription_date
	 * @param unsubscriptionDate  the value for aventador.member_account.unsubscription_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setUnsubscriptionDate(LocalDateTime unsubscriptionDate) {
		this.unsubscriptionDate = unsubscriptionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.password_expiration_date
	 * @return  the value of aventador.member_account.password_expiration_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public LocalDateTime getPasswordExpirationDate() {
		return passwordExpirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.password_expiration_date
	 * @param passwordExpirationDate  the value for aventador.member_account.password_expiration_date
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setPasswordExpirationDate(LocalDateTime passwordExpirationDate) {
		this.passwordExpirationDate = passwordExpirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_account.etc_info
	 * @return  the value of aventador.member_account.etc_info
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public String getEtcInfo() {
		return etcInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_account.etc_info
	 * @param etcInfo  the value for aventador.member_account.etc_info
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setEtcInfo(String etcInfo) {
		this.etcInfo = etcInfo;
	}
}