package com.ocko.aventador.dao.model.aventador;

import java.util.ArrayList;
import java.util.List;
import java.time.LocalDateTime;

public class MemberSettingExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table {0}
	 * @mbggenerated
	 */
	private Integer limit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table {0}
	 * @mbggenerated
	 */
	private Integer offset;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public MemberSettingExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table {0}
	 * @mbggenerated
	 */
	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table {0}
	 * @mbggenerated
	 */
	public Integer getLimit() {
		return limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table {0}
	 * @mbggenerated
	 */
	public void setOffset(Integer offset) {
		this.offset = offset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table {0}
	 * @mbggenerated
	 */
	public Integer getOffset() {
		return offset;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMemberIdIsNull() {
			addCriterion("member_id is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNotNull() {
			addCriterion("member_id is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdEqualTo(Integer value) {
			addCriterion("member_id =", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotEqualTo(Integer value) {
			addCriterion("member_id <>", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThan(Integer value) {
			addCriterion("member_id >", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_id >=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThan(Integer value) {
			addCriterion("member_id <", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
			addCriterion("member_id <=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdIn(List<Integer> values) {
			addCriterion("member_id in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotIn(List<Integer> values) {
			addCriterion("member_id not in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdBetween(Integer value1, Integer value2) {
			addCriterion("member_id between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
			addCriterion("member_id not between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andSettingDetailIsNull() {
			addCriterion("setting_detail is null");
			return (Criteria) this;
		}

		public Criteria andSettingDetailIsNotNull() {
			addCriterion("setting_detail is not null");
			return (Criteria) this;
		}

		public Criteria andSettingDetailEqualTo(String value) {
			addCriterion("setting_detail =", value, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailNotEqualTo(String value) {
			addCriterion("setting_detail <>", value, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailGreaterThan(String value) {
			addCriterion("setting_detail >", value, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailGreaterThanOrEqualTo(String value) {
			addCriterion("setting_detail >=", value, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailLessThan(String value) {
			addCriterion("setting_detail <", value, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailLessThanOrEqualTo(String value) {
			addCriterion("setting_detail <=", value, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailIn(List<String> values) {
			addCriterion("setting_detail in", values, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailNotIn(List<String> values) {
			addCriterion("setting_detail not in", values, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailBetween(String value1, String value2) {
			addCriterion("setting_detail between", value1, value2, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andSettingDetailNotBetween(String value1, String value2) {
			addCriterion("setting_detail not between", value1, value2, "settingDetail");
			return (Criteria) this;
		}

		public Criteria andApiKeyIsNull() {
			addCriterion("api_key is null");
			return (Criteria) this;
		}

		public Criteria andApiKeyIsNotNull() {
			addCriterion("api_key is not null");
			return (Criteria) this;
		}

		public Criteria andApiKeyEqualTo(String value) {
			addCriterion("api_key =", value, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyNotEqualTo(String value) {
			addCriterion("api_key <>", value, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyGreaterThan(String value) {
			addCriterion("api_key >", value, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyGreaterThanOrEqualTo(String value) {
			addCriterion("api_key >=", value, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyLessThan(String value) {
			addCriterion("api_key <", value, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyLessThanOrEqualTo(String value) {
			addCriterion("api_key <=", value, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyLike(String value) {
			addCriterion("api_key like", value, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyNotLike(String value) {
			addCriterion("api_key not like", value, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyIn(List<String> values) {
			addCriterion("api_key in", values, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyNotIn(List<String> values) {
			addCriterion("api_key not in", values, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyBetween(String value1, String value2) {
			addCriterion("api_key between", value1, value2, "apiKey");
			return (Criteria) this;
		}

		public Criteria andApiKeyNotBetween(String value1, String value2) {
			addCriterion("api_key not between", value1, value2, "apiKey");
			return (Criteria) this;
		}

		public Criteria andFcmTokenIsNull() {
			addCriterion("fcm_token is null");
			return (Criteria) this;
		}

		public Criteria andFcmTokenIsNotNull() {
			addCriterion("fcm_token is not null");
			return (Criteria) this;
		}

		public Criteria andFcmTokenEqualTo(String value) {
			addCriterion("fcm_token =", value, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenNotEqualTo(String value) {
			addCriterion("fcm_token <>", value, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenGreaterThan(String value) {
			addCriterion("fcm_token >", value, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenGreaterThanOrEqualTo(String value) {
			addCriterion("fcm_token >=", value, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenLessThan(String value) {
			addCriterion("fcm_token <", value, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenLessThanOrEqualTo(String value) {
			addCriterion("fcm_token <=", value, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenLike(String value) {
			addCriterion("fcm_token like", value, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenNotLike(String value) {
			addCriterion("fcm_token not like", value, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenIn(List<String> values) {
			addCriterion("fcm_token in", values, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenNotIn(List<String> values) {
			addCriterion("fcm_token not in", values, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenBetween(String value1, String value2) {
			addCriterion("fcm_token between", value1, value2, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andFcmTokenNotBetween(String value1, String value2) {
			addCriterion("fcm_token not between", value1, value2, "fcmToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenIsNull() {
			addCriterion("check_token is null");
			return (Criteria) this;
		}

		public Criteria andCheckTokenIsNotNull() {
			addCriterion("check_token is not null");
			return (Criteria) this;
		}

		public Criteria andCheckTokenEqualTo(String value) {
			addCriterion("check_token =", value, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenNotEqualTo(String value) {
			addCriterion("check_token <>", value, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenGreaterThan(String value) {
			addCriterion("check_token >", value, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenGreaterThanOrEqualTo(String value) {
			addCriterion("check_token >=", value, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenLessThan(String value) {
			addCriterion("check_token <", value, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenLessThanOrEqualTo(String value) {
			addCriterion("check_token <=", value, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenLike(String value) {
			addCriterion("check_token like", value, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenNotLike(String value) {
			addCriterion("check_token not like", value, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenIn(List<String> values) {
			addCriterion("check_token in", values, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenNotIn(List<String> values) {
			addCriterion("check_token not in", values, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenBetween(String value1, String value2) {
			addCriterion("check_token between", value1, value2, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenNotBetween(String value1, String value2) {
			addCriterion("check_token not between", value1, value2, "checkToken");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableIsNull() {
			addCriterion("check_token_available is null");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableIsNotNull() {
			addCriterion("check_token_available is not null");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableEqualTo(LocalDateTime value) {
			addCriterion("check_token_available =", value, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableNotEqualTo(LocalDateTime value) {
			addCriterion("check_token_available <>", value, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableGreaterThan(LocalDateTime value) {
			addCriterion("check_token_available >", value, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("check_token_available >=", value, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableLessThan(LocalDateTime value) {
			addCriterion("check_token_available <", value, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("check_token_available <=", value, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableIn(List<LocalDateTime> values) {
			addCriterion("check_token_available in", values, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableNotIn(List<LocalDateTime> values) {
			addCriterion("check_token_available not in", values, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("check_token_available between", value1, value2, "checkTokenAvailable");
			return (Criteria) this;
		}

		public Criteria andCheckTokenAvailableNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("check_token_available not between", value1, value2, "checkTokenAvailable");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aventador.member_setting
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 23 22:09:51 KST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}