package com.ocko.aventador.dao.model.aventador;

public class MemberSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.member_setting.member_id
     *
     * @mbg.generated Thu Dec 23 22:09:51 KST 2021
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.member_setting.setting_detail
     *
     * @mbg.generated Thu Dec 23 22:09:51 KST 2021
     */
    private String settingDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.member_setting.member_id
     *
     * @return the value of aventador.member_setting.member_id
     *
     * @mbg.generated Thu Dec 23 22:09:51 KST 2021
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.member_setting.member_id
     *
     * @param memberId the value for aventador.member_setting.member_id
     *
     * @mbg.generated Thu Dec 23 22:09:51 KST 2021
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.member_setting.setting_detail
     *
     * @return the value of aventador.member_setting.setting_detail
     *
     * @mbg.generated Thu Dec 23 22:09:51 KST 2021
     */
    public String getSettingDetail() {
        return settingDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.member_setting.setting_detail
     *
     * @param settingDetail the value for aventador.member_setting.setting_detail
     *
     * @mbg.generated Thu Dec 23 22:09:51 KST 2021
     */
    public void setSettingDetail(String settingDetail) {
        this.settingDetail = settingDetail;
    }
}