package com.ocko.aventador.dao.model.aventador;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.time.LocalDateTime;

public class MemberAccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table {0}
	 * @mbggenerated
	 */
	private Integer limit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table {0}
	 * @mbggenerated
	 */
	private Integer offset;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public MemberAccountExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table {0}
	 * @mbggenerated
	 */
	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table {0}
	 * @mbggenerated
	 */
	public Integer getLimit() {
		return limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table {0}
	 * @mbggenerated
	 */
	public void setOffset(Integer offset) {
		this.offset = offset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table {0}
	 * @mbggenerated
	 */
	public Integer getOffset() {
		return offset;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMemberIdIsNull() {
			addCriterion("member_id is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNotNull() {
			addCriterion("member_id is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdEqualTo(Integer value) {
			addCriterion("member_id =", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotEqualTo(Integer value) {
			addCriterion("member_id <>", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThan(Integer value) {
			addCriterion("member_id >", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_id >=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThan(Integer value) {
			addCriterion("member_id <", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
			addCriterion("member_id <=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdIn(List<Integer> values) {
			addCriterion("member_id in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotIn(List<Integer> values) {
			addCriterion("member_id not in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdBetween(Integer value1, Integer value2) {
			addCriterion("member_id between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
			addCriterion("member_id not between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberEmailIsNull() {
			addCriterion("member_email is null");
			return (Criteria) this;
		}

		public Criteria andMemberEmailIsNotNull() {
			addCriterion("member_email is not null");
			return (Criteria) this;
		}

		public Criteria andMemberEmailEqualTo(String value) {
			addCriterion("member_email =", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailNotEqualTo(String value) {
			addCriterion("member_email <>", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailGreaterThan(String value) {
			addCriterion("member_email >", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailGreaterThanOrEqualTo(String value) {
			addCriterion("member_email >=", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailLessThan(String value) {
			addCriterion("member_email <", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailLessThanOrEqualTo(String value) {
			addCriterion("member_email <=", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailLike(String value) {
			addCriterion("member_email like", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailNotLike(String value) {
			addCriterion("member_email not like", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailIn(List<String> values) {
			addCriterion("member_email in", values, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailNotIn(List<String> values) {
			addCriterion("member_email not in", values, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailBetween(String value1, String value2) {
			addCriterion("member_email between", value1, value2, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailNotBetween(String value1, String value2) {
			addCriterion("member_email not between", value1, value2, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberNameIsNull() {
			addCriterion("member_name is null");
			return (Criteria) this;
		}

		public Criteria andMemberNameIsNotNull() {
			addCriterion("member_name is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNameEqualTo(String value) {
			addCriterion("member_name =", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotEqualTo(String value) {
			addCriterion("member_name <>", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameGreaterThan(String value) {
			addCriterion("member_name >", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameGreaterThanOrEqualTo(String value) {
			addCriterion("member_name >=", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLessThan(String value) {
			addCriterion("member_name <", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLessThanOrEqualTo(String value) {
			addCriterion("member_name <=", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLike(String value) {
			addCriterion("member_name like", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotLike(String value) {
			addCriterion("member_name not like", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameIn(List<String> values) {
			addCriterion("member_name in", values, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotIn(List<String> values) {
			addCriterion("member_name not in", values, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameBetween(String value1, String value2) {
			addCriterion("member_name between", value1, value2, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotBetween(String value1, String value2) {
			addCriterion("member_name not between", value1, value2, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordIsNull() {
			addCriterion("member_password is null");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordIsNotNull() {
			addCriterion("member_password is not null");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordEqualTo(String value) {
			addCriterion("member_password =", value, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordNotEqualTo(String value) {
			addCriterion("member_password <>", value, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordGreaterThan(String value) {
			addCriterion("member_password >", value, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("member_password >=", value, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordLessThan(String value) {
			addCriterion("member_password <", value, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordLessThanOrEqualTo(String value) {
			addCriterion("member_password <=", value, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordLike(String value) {
			addCriterion("member_password like", value, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordNotLike(String value) {
			addCriterion("member_password not like", value, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordIn(List<String> values) {
			addCriterion("member_password in", values, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordNotIn(List<String> values) {
			addCriterion("member_password not in", values, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordBetween(String value1, String value2) {
			addCriterion("member_password between", value1, value2, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberPasswordNotBetween(String value1, String value2) {
			addCriterion("member_password not between", value1, value2, "memberPassword");
			return (Criteria) this;
		}

		public Criteria andMemberStatusIsNull() {
			addCriterion("member_status is null");
			return (Criteria) this;
		}

		public Criteria andMemberStatusIsNotNull() {
			addCriterion("member_status is not null");
			return (Criteria) this;
		}

		public Criteria andMemberStatusEqualTo(String value) {
			addCriterion("member_status =", value, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusNotEqualTo(String value) {
			addCriterion("member_status <>", value, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusGreaterThan(String value) {
			addCriterion("member_status >", value, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusGreaterThanOrEqualTo(String value) {
			addCriterion("member_status >=", value, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusLessThan(String value) {
			addCriterion("member_status <", value, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusLessThanOrEqualTo(String value) {
			addCriterion("member_status <=", value, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusLike(String value) {
			addCriterion("member_status like", value, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusNotLike(String value) {
			addCriterion("member_status not like", value, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusIn(List<String> values) {
			addCriterion("member_status in", values, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusNotIn(List<String> values) {
			addCriterion("member_status not in", values, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusBetween(String value1, String value2) {
			addCriterion("member_status between", value1, value2, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberStatusNotBetween(String value1, String value2) {
			addCriterion("member_status not between", value1, value2, "memberStatus");
			return (Criteria) this;
		}

		public Criteria andMemberRolesIsNull() {
			addCriterion("member_roles is null");
			return (Criteria) this;
		}

		public Criteria andMemberRolesIsNotNull() {
			addCriterion("member_roles is not null");
			return (Criteria) this;
		}

		public Criteria andMemberRolesEqualTo(String value) {
			addCriterion("member_roles =", value, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesNotEqualTo(String value) {
			addCriterion("member_roles <>", value, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesGreaterThan(String value) {
			addCriterion("member_roles >", value, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesGreaterThanOrEqualTo(String value) {
			addCriterion("member_roles >=", value, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesLessThan(String value) {
			addCriterion("member_roles <", value, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesLessThanOrEqualTo(String value) {
			addCriterion("member_roles <=", value, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesLike(String value) {
			addCriterion("member_roles like", value, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesNotLike(String value) {
			addCriterion("member_roles not like", value, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesIn(List<String> values) {
			addCriterion("member_roles in", values, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesNotIn(List<String> values) {
			addCriterion("member_roles not in", values, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesBetween(String value1, String value2) {
			addCriterion("member_roles between", value1, value2, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andMemberRolesNotBetween(String value1, String value2) {
			addCriterion("member_roles not between", value1, value2, "memberRoles");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateIsNull() {
			addCriterion("subscription_date is null");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateIsNotNull() {
			addCriterion("subscription_date is not null");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateEqualTo(LocalDateTime value) {
			addCriterion("subscription_date =", value, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateNotEqualTo(LocalDateTime value) {
			addCriterion("subscription_date <>", value, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateGreaterThan(LocalDateTime value) {
			addCriterion("subscription_date >", value, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("subscription_date >=", value, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateLessThan(LocalDateTime value) {
			addCriterion("subscription_date <", value, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("subscription_date <=", value, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateIn(List<LocalDateTime> values) {
			addCriterion("subscription_date in", values, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateNotIn(List<LocalDateTime> values) {
			addCriterion("subscription_date not in", values, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("subscription_date between", value1, value2, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andSubscriptionDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("subscription_date not between", value1, value2, "subscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateIsNull() {
			addCriterion("unsubscription_date is null");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateIsNotNull() {
			addCriterion("unsubscription_date is not null");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateEqualTo(LocalDateTime value) {
			addCriterion("unsubscription_date =", value, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateNotEqualTo(LocalDateTime value) {
			addCriterion("unsubscription_date <>", value, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateGreaterThan(LocalDateTime value) {
			addCriterion("unsubscription_date >", value, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("unsubscription_date >=", value, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateLessThan(LocalDateTime value) {
			addCriterion("unsubscription_date <", value, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("unsubscription_date <=", value, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateIn(List<LocalDateTime> values) {
			addCriterion("unsubscription_date in", values, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateNotIn(List<LocalDateTime> values) {
			addCriterion("unsubscription_date not in", values, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("unsubscription_date between", value1, value2, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andUnsubscriptionDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("unsubscription_date not between", value1, value2, "unsubscriptionDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateIsNull() {
			addCriterion("password_expiration_date is null");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateIsNotNull() {
			addCriterion("password_expiration_date is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateEqualTo(LocalDateTime value) {
			addCriterion("password_expiration_date =", value, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateNotEqualTo(LocalDateTime value) {
			addCriterion("password_expiration_date <>", value, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateGreaterThan(LocalDateTime value) {
			addCriterion("password_expiration_date >", value, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("password_expiration_date >=", value, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateLessThan(LocalDateTime value) {
			addCriterion("password_expiration_date <", value, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("password_expiration_date <=", value, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateIn(List<LocalDateTime> values) {
			addCriterion("password_expiration_date in", values, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateNotIn(List<LocalDateTime> values) {
			addCriterion("password_expiration_date not in", values, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("password_expiration_date between", value1, value2, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andPasswordExpirationDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("password_expiration_date not between", value1, value2, "passwordExpirationDate");
			return (Criteria) this;
		}

		public Criteria andEtcInfoIsNull() {
			addCriterion("etc_info is null");
			return (Criteria) this;
		}

		public Criteria andEtcInfoIsNotNull() {
			addCriterion("etc_info is not null");
			return (Criteria) this;
		}

		public Criteria andEtcInfoEqualTo(String value) {
			addCriterion("etc_info =", value, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoNotEqualTo(String value) {
			addCriterion("etc_info <>", value, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoGreaterThan(String value) {
			addCriterion("etc_info >", value, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoGreaterThanOrEqualTo(String value) {
			addCriterion("etc_info >=", value, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoLessThan(String value) {
			addCriterion("etc_info <", value, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoLessThanOrEqualTo(String value) {
			addCriterion("etc_info <=", value, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoIn(List<String> values) {
			addCriterion("etc_info in", values, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoNotIn(List<String> values) {
			addCriterion("etc_info not in", values, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoBetween(String value1, String value2) {
			addCriterion("etc_info between", value1, value2, "etcInfo");
			return (Criteria) this;
		}

		public Criteria andEtcInfoNotBetween(String value1, String value2) {
			addCriterion("etc_info not between", value1, value2, "etcInfo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table aventador.member_account
	 * @mbg.generated  Tue Nov 23 11:36:56 KST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aventador.member_account
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 19 23:41:28 KST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}