package com.ocko.aventador.dao.model.aventador;

import java.time.LocalDateTime;

public class MemberSetting {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_setting.member_id
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_setting.setting_detail
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	private String settingDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_setting.api_key
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	private String apiKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_setting.fcm_token
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	private String fcmToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.member_setting.refresh_token
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	private String refreshToken;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_setting.member_id
	 * @return  the value of aventador.member_setting.member_id
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_setting.member_id
	 * @param memberId  the value for aventador.member_setting.member_id
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_setting.setting_detail
	 * @return  the value of aventador.member_setting.setting_detail
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public String getSettingDetail() {
		return settingDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_setting.setting_detail
	 * @param settingDetail  the value for aventador.member_setting.setting_detail
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public void setSettingDetail(String settingDetail) {
		this.settingDetail = settingDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_setting.api_key
	 * @return  the value of aventador.member_setting.api_key
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public String getApiKey() {
		return apiKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_setting.api_key
	 * @param apiKey  the value for aventador.member_setting.api_key
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_setting.fcm_token
	 * @return  the value of aventador.member_setting.fcm_token
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public String getFcmToken() {
		return fcmToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_setting.fcm_token
	 * @param fcmToken  the value for aventador.member_setting.fcm_token
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public void setFcmToken(String fcmToken) {
		this.fcmToken = fcmToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.member_setting.refresh_token
	 * @return  the value of aventador.member_setting.refresh_token
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public String getRefreshToken() {
		return refreshToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.member_setting.refresh_token
	 * @param refreshToken  the value for aventador.member_setting.refresh_token
	 * @mbg.generated  Sat Apr 23 00:26:50 KST 2022
	 */
	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken;
	}
}