package com.ocko.aventador.dao.model.aventador;

import java.time.LocalDate;

public class ViewTodayStock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.symbol
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.stock_date
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private LocalDate stockDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.price_high
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Float priceHigh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.price_low
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Float priceLow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.price_close
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Float priceClose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.price_open
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Float priceOpen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.volume
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Long volume;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.rsi
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Float rsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.up_avg
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Float upAvg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.dw_avg
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Float dwAvg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_today_stock.prev_close
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	private Float prevClose;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.symbol
	 * @return  the value of aventador.view_today_stock.symbol
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.symbol
	 * @param symbol  the value for aventador.view_today_stock.symbol
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.stock_date
	 * @return  the value of aventador.view_today_stock.stock_date
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public LocalDate getStockDate() {
		return stockDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.stock_date
	 * @param stockDate  the value for aventador.view_today_stock.stock_date
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setStockDate(LocalDate stockDate) {
		this.stockDate = stockDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.price_high
	 * @return  the value of aventador.view_today_stock.price_high
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Float getPriceHigh() {
		return priceHigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.price_high
	 * @param priceHigh  the value for aventador.view_today_stock.price_high
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setPriceHigh(Float priceHigh) {
		this.priceHigh = priceHigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.price_low
	 * @return  the value of aventador.view_today_stock.price_low
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Float getPriceLow() {
		return priceLow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.price_low
	 * @param priceLow  the value for aventador.view_today_stock.price_low
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setPriceLow(Float priceLow) {
		this.priceLow = priceLow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.price_close
	 * @return  the value of aventador.view_today_stock.price_close
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Float getPriceClose() {
		return priceClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.price_close
	 * @param priceClose  the value for aventador.view_today_stock.price_close
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setPriceClose(Float priceClose) {
		this.priceClose = priceClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.price_open
	 * @return  the value of aventador.view_today_stock.price_open
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Float getPriceOpen() {
		return priceOpen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.price_open
	 * @param priceOpen  the value for aventador.view_today_stock.price_open
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setPriceOpen(Float priceOpen) {
		this.priceOpen = priceOpen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.volume
	 * @return  the value of aventador.view_today_stock.volume
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Long getVolume() {
		return volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.volume
	 * @param volume  the value for aventador.view_today_stock.volume
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setVolume(Long volume) {
		this.volume = volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.rsi
	 * @return  the value of aventador.view_today_stock.rsi
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Float getRsi() {
		return rsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.rsi
	 * @param rsi  the value for aventador.view_today_stock.rsi
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setRsi(Float rsi) {
		this.rsi = rsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.up_avg
	 * @return  the value of aventador.view_today_stock.up_avg
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Float getUpAvg() {
		return upAvg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.up_avg
	 * @param upAvg  the value for aventador.view_today_stock.up_avg
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setUpAvg(Float upAvg) {
		this.upAvg = upAvg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.dw_avg
	 * @return  the value of aventador.view_today_stock.dw_avg
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Float getDwAvg() {
		return dwAvg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.dw_avg
	 * @param dwAvg  the value for aventador.view_today_stock.dw_avg
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setDwAvg(Float dwAvg) {
		this.dwAvg = dwAvg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_today_stock.prev_close
	 * @return  the value of aventador.view_today_stock.prev_close
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public Float getPrevClose() {
		return prevClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_today_stock.prev_close
	 * @param prevClose  the value for aventador.view_today_stock.prev_close
	 * @mbg.generated  Thu Nov 25 16:39:35 KST 2021
	 */
	public void setPrevClose(Float prevClose) {
		this.prevClose = prevClose;
	}
}