package com.ocko.aventador.dao.model.aventador;

import java.math.BigDecimal;

public class ViewInfiniteProfitStock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.member_id
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.account_id
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.fees_per
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	private BigDecimal feesPer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.symbol
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.total_buy_price
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	private BigDecimal totalBuyPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.total_sell_price
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	private BigDecimal totalSellPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.member_id
	 * @return  the value of aventador.view_infinite_profit_stock.member_id
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.member_id
	 * @param memberId  the value for aventador.view_infinite_profit_stock.member_id
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.account_id
	 * @return  the value of aventador.view_infinite_profit_stock.account_id
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.account_id
	 * @param accountId  the value for aventador.view_infinite_profit_stock.account_id
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.fees_per
	 * @return  the value of aventador.view_infinite_profit_stock.fees_per
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public BigDecimal getFeesPer() {
		return feesPer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.fees_per
	 * @param feesPer  the value for aventador.view_infinite_profit_stock.fees_per
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public void setFeesPer(BigDecimal feesPer) {
		this.feesPer = feesPer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.symbol
	 * @return  the value of aventador.view_infinite_profit_stock.symbol
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.symbol
	 * @param symbol  the value for aventador.view_infinite_profit_stock.symbol
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.total_buy_price
	 * @return  the value of aventador.view_infinite_profit_stock.total_buy_price
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public BigDecimal getTotalBuyPrice() {
		return totalBuyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.total_buy_price
	 * @param totalBuyPrice  the value for aventador.view_infinite_profit_stock.total_buy_price
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public void setTotalBuyPrice(BigDecimal totalBuyPrice) {
		this.totalBuyPrice = totalBuyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.total_sell_price
	 * @return  the value of aventador.view_infinite_profit_stock.total_sell_price
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public BigDecimal getTotalSellPrice() {
		return totalSellPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.total_sell_price
	 * @param totalSellPrice  the value for aventador.view_infinite_profit_stock.total_sell_price
	 * @mbg.generated  Thu Mar 31 17:04:40 KST 2022
	 */
	public void setTotalSellPrice(BigDecimal totalSellPrice) {
		this.totalSellPrice = totalSellPrice;
	}
}