package com.ocko.aventador.dao.model.aventador;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class ViewInfiniteList {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.member_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.account_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.fees_per
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private BigDecimal feesPer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.infinite_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private Integer infiniteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.symbol
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.seed
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private BigDecimal seed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.infinite_type
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private String infiniteType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.infinite_state
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private String infiniteState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.started_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private LocalDate startedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.registered_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private LocalDateTime registeredDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.done_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private LocalDate doneDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.holding_quantity
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private Integer holdingQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.buy_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private BigDecimal buyPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.total_buy_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private BigDecimal totalBuyPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.total_sell_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	private BigDecimal totalSellPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.member_id
	 * @return  the value of aventador.view_infinite_list.member_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.member_id
	 * @param memberId  the value for aventador.view_infinite_list.member_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.account_id
	 * @return  the value of aventador.view_infinite_list.account_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.account_id
	 * @param accountId  the value for aventador.view_infinite_list.account_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.fees_per
	 * @return  the value of aventador.view_infinite_list.fees_per
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public BigDecimal getFeesPer() {
		return feesPer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.fees_per
	 * @param feesPer  the value for aventador.view_infinite_list.fees_per
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setFeesPer(BigDecimal feesPer) {
		this.feesPer = feesPer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.infinite_id
	 * @return  the value of aventador.view_infinite_list.infinite_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public Integer getInfiniteId() {
		return infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.infinite_id
	 * @param infiniteId  the value for aventador.view_infinite_list.infinite_id
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setInfiniteId(Integer infiniteId) {
		this.infiniteId = infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.symbol
	 * @return  the value of aventador.view_infinite_list.symbol
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.symbol
	 * @param symbol  the value for aventador.view_infinite_list.symbol
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.seed
	 * @return  the value of aventador.view_infinite_list.seed
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public BigDecimal getSeed() {
		return seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.seed
	 * @param seed  the value for aventador.view_infinite_list.seed
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setSeed(BigDecimal seed) {
		this.seed = seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.infinite_type
	 * @return  the value of aventador.view_infinite_list.infinite_type
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public String getInfiniteType() {
		return infiniteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.infinite_type
	 * @param infiniteType  the value for aventador.view_infinite_list.infinite_type
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setInfiniteType(String infiniteType) {
		this.infiniteType = infiniteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.infinite_state
	 * @return  the value of aventador.view_infinite_list.infinite_state
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public String getInfiniteState() {
		return infiniteState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.infinite_state
	 * @param infiniteState  the value for aventador.view_infinite_list.infinite_state
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setInfiniteState(String infiniteState) {
		this.infiniteState = infiniteState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.started_date
	 * @return  the value of aventador.view_infinite_list.started_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public LocalDate getStartedDate() {
		return startedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.started_date
	 * @param startedDate  the value for aventador.view_infinite_list.started_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setStartedDate(LocalDate startedDate) {
		this.startedDate = startedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.registered_date
	 * @return  the value of aventador.view_infinite_list.registered_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public LocalDateTime getRegisteredDate() {
		return registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.registered_date
	 * @param registeredDate  the value for aventador.view_infinite_list.registered_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setRegisteredDate(LocalDateTime registeredDate) {
		this.registeredDate = registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.done_date
	 * @return  the value of aventador.view_infinite_list.done_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public LocalDate getDoneDate() {
		return doneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.done_date
	 * @param doneDate  the value for aventador.view_infinite_list.done_date
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setDoneDate(LocalDate doneDate) {
		this.doneDate = doneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.holding_quantity
	 * @return  the value of aventador.view_infinite_list.holding_quantity
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public Integer getHoldingQuantity() {
		return holdingQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.holding_quantity
	 * @param holdingQuantity  the value for aventador.view_infinite_list.holding_quantity
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setHoldingQuantity(Integer holdingQuantity) {
		this.holdingQuantity = holdingQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.buy_price
	 * @return  the value of aventador.view_infinite_list.buy_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public BigDecimal getBuyPrice() {
		return buyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.buy_price
	 * @param buyPrice  the value for aventador.view_infinite_list.buy_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setBuyPrice(BigDecimal buyPrice) {
		this.buyPrice = buyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.total_buy_price
	 * @return  the value of aventador.view_infinite_list.total_buy_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public BigDecimal getTotalBuyPrice() {
		return totalBuyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.total_buy_price
	 * @param totalBuyPrice  the value for aventador.view_infinite_list.total_buy_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setTotalBuyPrice(BigDecimal totalBuyPrice) {
		this.totalBuyPrice = totalBuyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.total_sell_price
	 * @return  the value of aventador.view_infinite_list.total_sell_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public BigDecimal getTotalSellPrice() {
		return totalSellPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.total_sell_price
	 * @param totalSellPrice  the value for aventador.view_infinite_list.total_sell_price
	 * @mbg.generated  Fri Jan 07 09:55:13 KST 2022
	 */
	public void setTotalSellPrice(BigDecimal totalSellPrice) {
		this.totalSellPrice = totalSellPrice;
	}
}