package com.ocko.aventador.dao.model.aventador;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class ViewInfiniteList {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.member_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.account_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.infinite_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private Integer infiniteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.symbol
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.seed
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private BigDecimal seed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.infinite_type
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private String infiniteType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.infinite_state
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private String infiniteState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.started_date
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private LocalDate startedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.registered_date
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private LocalDateTime registeredDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.holding_quantity
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private Integer holdingQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.average_price
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private BigDecimal averagePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_list.buy_price
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	private BigDecimal buyPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.member_id
	 * @return  the value of aventador.view_infinite_list.member_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.member_id
	 * @param memberId  the value for aventador.view_infinite_list.member_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.account_id
	 * @return  the value of aventador.view_infinite_list.account_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.account_id
	 * @param accountId  the value for aventador.view_infinite_list.account_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.infinite_id
	 * @return  the value of aventador.view_infinite_list.infinite_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public Integer getInfiniteId() {
		return infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.infinite_id
	 * @param infiniteId  the value for aventador.view_infinite_list.infinite_id
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setInfiniteId(Integer infiniteId) {
		this.infiniteId = infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.symbol
	 * @return  the value of aventador.view_infinite_list.symbol
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.symbol
	 * @param symbol  the value for aventador.view_infinite_list.symbol
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.seed
	 * @return  the value of aventador.view_infinite_list.seed
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public BigDecimal getSeed() {
		return seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.seed
	 * @param seed  the value for aventador.view_infinite_list.seed
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setSeed(BigDecimal seed) {
		this.seed = seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.infinite_type
	 * @return  the value of aventador.view_infinite_list.infinite_type
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public String getInfiniteType() {
		return infiniteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.infinite_type
	 * @param infiniteType  the value for aventador.view_infinite_list.infinite_type
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setInfiniteType(String infiniteType) {
		this.infiniteType = infiniteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.infinite_state
	 * @return  the value of aventador.view_infinite_list.infinite_state
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public String getInfiniteState() {
		return infiniteState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.infinite_state
	 * @param infiniteState  the value for aventador.view_infinite_list.infinite_state
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setInfiniteState(String infiniteState) {
		this.infiniteState = infiniteState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.started_date
	 * @return  the value of aventador.view_infinite_list.started_date
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public LocalDate getStartedDate() {
		return startedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.started_date
	 * @param startedDate  the value for aventador.view_infinite_list.started_date
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setStartedDate(LocalDate startedDate) {
		this.startedDate = startedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.registered_date
	 * @return  the value of aventador.view_infinite_list.registered_date
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public LocalDateTime getRegisteredDate() {
		return registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.registered_date
	 * @param registeredDate  the value for aventador.view_infinite_list.registered_date
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setRegisteredDate(LocalDateTime registeredDate) {
		this.registeredDate = registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.holding_quantity
	 * @return  the value of aventador.view_infinite_list.holding_quantity
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public Integer getHoldingQuantity() {
		return holdingQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.holding_quantity
	 * @param holdingQuantity  the value for aventador.view_infinite_list.holding_quantity
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setHoldingQuantity(Integer holdingQuantity) {
		this.holdingQuantity = holdingQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.average_price
	 * @return  the value of aventador.view_infinite_list.average_price
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public BigDecimal getAveragePrice() {
		return averagePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.average_price
	 * @param averagePrice  the value for aventador.view_infinite_list.average_price
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setAveragePrice(BigDecimal averagePrice) {
		this.averagePrice = averagePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_list.buy_price
	 * @return  the value of aventador.view_infinite_list.buy_price
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public BigDecimal getBuyPrice() {
		return buyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_list.buy_price
	 * @param buyPrice  the value for aventador.view_infinite_list.buy_price
	 * @mbg.generated  Thu Dec 09 14:32:10 KST 2021
	 */
	public void setBuyPrice(BigDecimal buyPrice) {
		this.buyPrice = buyPrice;
	}
}