package com.ocko.aventador.dao.model.aventador;

import java.math.BigDecimal;
import java.time.LocalDate;

public class ViewInfiniteBuyDaily {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_buy_daily.member_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_buy_daily.account_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_buy_daily.infinite_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	private Integer infiniteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_buy_daily.symbol
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_buy_daily.seed
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	private BigDecimal seed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_buy_daily.kskyj_seed
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	private BigDecimal kskyjSeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_buy_daily.trade_date
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	private LocalDate tradeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_buy_daily.trade_price
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	private BigDecimal tradePrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_buy_daily.member_id
	 * @return  the value of aventador.view_infinite_buy_daily.member_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_buy_daily.member_id
	 * @param memberId  the value for aventador.view_infinite_buy_daily.member_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_buy_daily.account_id
	 * @return  the value of aventador.view_infinite_buy_daily.account_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_buy_daily.account_id
	 * @param accountId  the value for aventador.view_infinite_buy_daily.account_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_buy_daily.infinite_id
	 * @return  the value of aventador.view_infinite_buy_daily.infinite_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public Integer getInfiniteId() {
		return infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_buy_daily.infinite_id
	 * @param infiniteId  the value for aventador.view_infinite_buy_daily.infinite_id
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public void setInfiniteId(Integer infiniteId) {
		this.infiniteId = infiniteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_buy_daily.symbol
	 * @return  the value of aventador.view_infinite_buy_daily.symbol
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_buy_daily.symbol
	 * @param symbol  the value for aventador.view_infinite_buy_daily.symbol
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_buy_daily.seed
	 * @return  the value of aventador.view_infinite_buy_daily.seed
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public BigDecimal getSeed() {
		return seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_buy_daily.seed
	 * @param seed  the value for aventador.view_infinite_buy_daily.seed
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public void setSeed(BigDecimal seed) {
		this.seed = seed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_buy_daily.kskyj_seed
	 * @return  the value of aventador.view_infinite_buy_daily.kskyj_seed
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public BigDecimal getKskyjSeed() {
		return kskyjSeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_buy_daily.kskyj_seed
	 * @param kskyjSeed  the value for aventador.view_infinite_buy_daily.kskyj_seed
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public void setKskyjSeed(BigDecimal kskyjSeed) {
		this.kskyjSeed = kskyjSeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_buy_daily.trade_date
	 * @return  the value of aventador.view_infinite_buy_daily.trade_date
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public LocalDate getTradeDate() {
		return tradeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_buy_daily.trade_date
	 * @param tradeDate  the value for aventador.view_infinite_buy_daily.trade_date
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public void setTradeDate(LocalDate tradeDate) {
		this.tradeDate = tradeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_buy_daily.trade_price
	 * @return  the value of aventador.view_infinite_buy_daily.trade_price
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public BigDecimal getTradePrice() {
		return tradePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_buy_daily.trade_price
	 * @param tradePrice  the value for aventador.view_infinite_buy_daily.trade_price
	 * @mbg.generated  Tue Feb 08 21:20:29 KST 2022
	 */
	public void setTradePrice(BigDecimal tradePrice) {
		this.tradePrice = tradePrice;
	}
}