package com.ocko.aventador.dao.model.aventador;

import java.math.BigDecimal;

public class ViewInfiniteBuyDaily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_buy_daily.member_id
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_buy_daily.account_id
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_buy_daily.daily
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    private String daily;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_buy_daily.buy_price
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    private BigDecimal buyPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_buy_daily.member_id
     *
     * @return the value of aventador.view_infinite_buy_daily.member_id
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_buy_daily.member_id
     *
     * @param memberId the value for aventador.view_infinite_buy_daily.member_id
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_buy_daily.account_id
     *
     * @return the value of aventador.view_infinite_buy_daily.account_id
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_buy_daily.account_id
     *
     * @param accountId the value for aventador.view_infinite_buy_daily.account_id
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_buy_daily.daily
     *
     * @return the value of aventador.view_infinite_buy_daily.daily
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    public String getDaily() {
        return daily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_buy_daily.daily
     *
     * @param daily the value for aventador.view_infinite_buy_daily.daily
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    public void setDaily(String daily) {
        this.daily = daily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_buy_daily.buy_price
     *
     * @return the value of aventador.view_infinite_buy_daily.buy_price
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_buy_daily.buy_price
     *
     * @param buyPrice the value for aventador.view_infinite_buy_daily.buy_price
     *
     * @mbg.generated Wed Dec 15 13:59:06 KST 2021
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }
}