package com.ocko.aventador.dao.model.aventador;

import java.math.BigDecimal;

public class ViewInfiniteProfitStock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.member_id
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	private Integer memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.account_id
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.symbol
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column aventador.view_infinite_profit_stock.profit
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	private BigDecimal profit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.member_id
	 * @return  the value of aventador.view_infinite_profit_stock.member_id
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.member_id
	 * @param memberId  the value for aventador.view_infinite_profit_stock.member_id
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.account_id
	 * @return  the value of aventador.view_infinite_profit_stock.account_id
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.account_id
	 * @param accountId  the value for aventador.view_infinite_profit_stock.account_id
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.symbol
	 * @return  the value of aventador.view_infinite_profit_stock.symbol
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.symbol
	 * @param symbol  the value for aventador.view_infinite_profit_stock.symbol
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column aventador.view_infinite_profit_stock.profit
	 * @return  the value of aventador.view_infinite_profit_stock.profit
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	public BigDecimal getProfit() {
		return profit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column aventador.view_infinite_profit_stock.profit
	 * @param profit  the value for aventador.view_infinite_profit_stock.profit
	 * @mbg.generated  Wed Dec 15 13:59:06 KST 2021
	 */
	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}
}