package com.ocko.aventador.dao.model.aventador;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class ViewInfiniteIncome {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.member_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.symbol
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.started_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private LocalDate startedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.seed
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private BigDecimal seed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.income_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private Integer incomeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.account_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.infinite_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private Integer infiniteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.infinite_history_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private Integer infiniteHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.sell_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private LocalDate sellDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.progress_per
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private BigDecimal progressPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.average_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private BigDecimal averagePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.buy_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private BigDecimal buyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.sell_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private BigDecimal sellPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private BigDecimal income;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.fees
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private BigDecimal fees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.registered_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private LocalDateTime registeredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aventador.view_infinite_income.is_deleted
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.member_id
     *
     * @return the value of aventador.view_infinite_income.member_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.member_id
     *
     * @param memberId the value for aventador.view_infinite_income.member_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.symbol
     *
     * @return the value of aventador.view_infinite_income.symbol
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.symbol
     *
     * @param symbol the value for aventador.view_infinite_income.symbol
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.started_date
     *
     * @return the value of aventador.view_infinite_income.started_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public LocalDate getStartedDate() {
        return startedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.started_date
     *
     * @param startedDate the value for aventador.view_infinite_income.started_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setStartedDate(LocalDate startedDate) {
        this.startedDate = startedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.seed
     *
     * @return the value of aventador.view_infinite_income.seed
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public BigDecimal getSeed() {
        return seed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.seed
     *
     * @param seed the value for aventador.view_infinite_income.seed
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setSeed(BigDecimal seed) {
        this.seed = seed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.income_id
     *
     * @return the value of aventador.view_infinite_income.income_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public Integer getIncomeId() {
        return incomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.income_id
     *
     * @param incomeId the value for aventador.view_infinite_income.income_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setIncomeId(Integer incomeId) {
        this.incomeId = incomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.account_id
     *
     * @return the value of aventador.view_infinite_income.account_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.account_id
     *
     * @param accountId the value for aventador.view_infinite_income.account_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.infinite_id
     *
     * @return the value of aventador.view_infinite_income.infinite_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public Integer getInfiniteId() {
        return infiniteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.infinite_id
     *
     * @param infiniteId the value for aventador.view_infinite_income.infinite_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setInfiniteId(Integer infiniteId) {
        this.infiniteId = infiniteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.infinite_history_id
     *
     * @return the value of aventador.view_infinite_income.infinite_history_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public Integer getInfiniteHistoryId() {
        return infiniteHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.infinite_history_id
     *
     * @param infiniteHistoryId the value for aventador.view_infinite_income.infinite_history_id
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setInfiniteHistoryId(Integer infiniteHistoryId) {
        this.infiniteHistoryId = infiniteHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.sell_date
     *
     * @return the value of aventador.view_infinite_income.sell_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public LocalDate getSellDate() {
        return sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.sell_date
     *
     * @param sellDate the value for aventador.view_infinite_income.sell_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setSellDate(LocalDate sellDate) {
        this.sellDate = sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.progress_per
     *
     * @return the value of aventador.view_infinite_income.progress_per
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public BigDecimal getProgressPer() {
        return progressPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.progress_per
     *
     * @param progressPer the value for aventador.view_infinite_income.progress_per
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setProgressPer(BigDecimal progressPer) {
        this.progressPer = progressPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.average_price
     *
     * @return the value of aventador.view_infinite_income.average_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public BigDecimal getAveragePrice() {
        return averagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.average_price
     *
     * @param averagePrice the value for aventador.view_infinite_income.average_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setAveragePrice(BigDecimal averagePrice) {
        this.averagePrice = averagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.buy_price
     *
     * @return the value of aventador.view_infinite_income.buy_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.buy_price
     *
     * @param buyPrice the value for aventador.view_infinite_income.buy_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.sell_price
     *
     * @return the value of aventador.view_infinite_income.sell_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.sell_price
     *
     * @param sellPrice the value for aventador.view_infinite_income.sell_price
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.income
     *
     * @return the value of aventador.view_infinite_income.income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public BigDecimal getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.income
     *
     * @param income the value for aventador.view_infinite_income.income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.fees
     *
     * @return the value of aventador.view_infinite_income.fees
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public BigDecimal getFees() {
        return fees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.fees
     *
     * @param fees the value for aventador.view_infinite_income.fees
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setFees(BigDecimal fees) {
        this.fees = fees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.registered_date
     *
     * @return the value of aventador.view_infinite_income.registered_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public LocalDateTime getRegisteredDate() {
        return registeredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.registered_date
     *
     * @param registeredDate the value for aventador.view_infinite_income.registered_date
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setRegisteredDate(LocalDateTime registeredDate) {
        this.registeredDate = registeredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aventador.view_infinite_income.is_deleted
     *
     * @return the value of aventador.view_infinite_income.is_deleted
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aventador.view_infinite_income.is_deleted
     *
     * @param isDeleted the value for aventador.view_infinite_income.is_deleted
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}