package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.InfiniteIncome;
import com.ocko.aventador.dao.model.aventador.InfiniteIncomeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface InfiniteIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    long countByExample(InfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.infinite_income.
     * 
     * @mbggenerated
     */
    void truncate();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    int deleteByExample(InfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    int deleteByPrimaryKey(Integer incomeId);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.infinite_income.
     *
     * @mbggenerated
     */
    int insertIgnore(InfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.infinite_income.
     *
     * @mbggenerated
     */
    int upsert(InfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    int insert(InfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    int insertSelective(InfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.infinite_income.
     *
     * @mbggenerated
     */
    Cursor<InfiniteIncome> cursorByExample(InfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.infinite_income.
     *
     * @mbggenerated
     */
    List<List<InfiniteIncome>> selectPksByExample(InfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    List<InfiniteIncome> selectByExample(InfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    InfiniteIncome selectByPrimaryKey(Integer incomeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    int updateByExampleSelective(@Param("record") InfiniteIncome record, @Param("example") InfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    int updateByExample(@Param("record") InfiniteIncome record, @Param("example") InfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    int updateByPrimaryKeySelective(InfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.infinite_income
     *
     * @mbg.generated Tue Apr 12 18:13:31 KST 2022
     */
    int updateByPrimaryKey(InfiniteIncome record);
}