package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.InfiniteHistory;
import com.ocko.aventador.dao.model.aventador.InfiniteHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface InfiniteHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	long countByExample(InfiniteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.infinite_history.
	 * @mbggenerated
	 */
	void truncate();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	int deleteByExample(InfiniteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	int deleteByPrimaryKey(Integer infiniteHistoryId);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.infinite_history.
	 * @mbggenerated
	 */
	int insertIgnore(InfiniteHistory record);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.infinite_history.
	 * @mbggenerated
	 */
	int upsert(InfiniteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	int insert(InfiniteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	int insertSelective(InfiniteHistory record);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.infinite_history.
	 * @mbggenerated
	 */
	Cursor<InfiniteHistory> cursorByExample(InfiniteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.infinite_history.
	 * @mbggenerated
	 */
	List<List<InfiniteHistory>> selectPksByExample(InfiniteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	List<InfiniteHistory> selectByExample(InfiniteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	InfiniteHistory selectByPrimaryKey(Integer infiniteHistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	int updateByExampleSelective(@Param("record") InfiniteHistory record,
			@Param("example") InfiniteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	int updateByExample(@Param("record") InfiniteHistory record, @Param("example") InfiniteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	int updateByPrimaryKeySelective(InfiniteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.infinite_history
	 * @mbg.generated  Mon Dec 06 00:26:07 KST 2021
	 */
	int updateByPrimaryKey(InfiniteHistory record);
}