package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.MemberAccount;
import com.ocko.aventador.dao.model.aventador.MemberAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface MemberAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    long countByExample(MemberAccountExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.member_account.
     * 
     * @mbggenerated
     */
    void truncate();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    int deleteByExample(MemberAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    int deleteByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.member_account.
     *
     * @mbggenerated
     */
    int insertIgnore(MemberAccount record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.member_account.
     *
     * @mbggenerated
     */
    int upsert(MemberAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    int insert(MemberAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    int insertSelective(MemberAccount record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.member_account.
     *
     * @mbggenerated
     */
    Cursor<MemberAccount> cursorByExample(MemberAccountExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.member_account.
     *
     * @mbggenerated
     */
    List<List<MemberAccount>> selectPksByExample(MemberAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    List<MemberAccount> selectByExample(MemberAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    MemberAccount selectByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    int updateByExampleSelective(@Param("record") MemberAccount record, @Param("example") MemberAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    int updateByExample(@Param("record") MemberAccount record, @Param("example") MemberAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    int updateByPrimaryKeySelective(MemberAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.member_account
     *
     * @mbg.generated Wed Dec 01 18:36:45 KST 2021
     */
    int updateByPrimaryKey(MemberAccount record);
}