package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.MemberSetting;
import com.ocko.aventador.dao.model.aventador.MemberSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface MemberSettingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	long countByExample(MemberSettingExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_setting.
	 * @mbggenerated
	 */
	void truncate();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	int deleteByExample(MemberSettingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	int deleteByPrimaryKey(Integer memberId);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_setting.
	 * @mbggenerated
	 */
	int insertIgnore(MemberSetting record);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_setting.
	 * @mbggenerated
	 */
	int upsert(MemberSetting record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	int insert(MemberSetting record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	int insertSelective(MemberSetting record);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_setting.
	 * @mbggenerated
	 */
	Cursor<MemberSetting> cursorByExample(MemberSettingExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_setting.
	 * @mbggenerated
	 */
	List<List<MemberSetting>> selectPksByExample(MemberSettingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	List<MemberSetting> selectByExample(MemberSettingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	MemberSetting selectByPrimaryKey(Integer memberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	int updateByExampleSelective(@Param("record") MemberSetting record, @Param("example") MemberSettingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	int updateByExample(@Param("record") MemberSetting record, @Param("example") MemberSettingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	int updateByPrimaryKeySelective(MemberSetting record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_setting
	 * @mbg.generated  Thu Jan 20 12:28:59 KST 2022
	 */
	int updateByPrimaryKey(MemberSetting record);
}