package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.MemberInfo;
import com.ocko.aventador.dao.model.aventador.MemberInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface MemberInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	long countByExample(MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_info.
	 * @mbggenerated
	 */
	void truncate();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	int deleteByExample(MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	int deleteByPrimaryKey(Integer memberId);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_info.
	 * @mbggenerated
	 */
	int insertIgnore(MemberInfo record);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_info.
	 * @mbggenerated
	 */
	int upsert(MemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	int insert(MemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	int insertSelective(MemberInfo record);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_info.
	 * @mbggenerated
	 */
	Cursor<MemberInfo> cursorByExample(MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.member_info.
	 * @mbggenerated
	 */
	List<List<MemberInfo>> selectPksByExample(MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	List<MemberInfo> selectByExample(MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	MemberInfo selectByPrimaryKey(Integer memberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	int updateByExampleSelective(@Param("record") MemberInfo record, @Param("example") MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	int updateByExample(@Param("record") MemberInfo record, @Param("example") MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	int updateByPrimaryKeySelective(MemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.member_info
	 * @mbg.generated  Thu Dec 02 22:23:22 KST 2021
	 */
	int updateByPrimaryKey(MemberInfo record);
}