package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.ServerStatus;
import com.ocko.aventador.dao.model.aventador.ServerStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface ServerStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    long countByExample(ServerStatusExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.server_status.
     * 
     * @mbggenerated
     */
    void truncate();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    int deleteByExample(ServerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    int deleteByPrimaryKey(String statusCode);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.server_status.
     *
     * @mbggenerated
     */
    int insertIgnore(ServerStatus record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.server_status.
     *
     * @mbggenerated
     */
    int upsert(ServerStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    int insert(ServerStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    int insertSelective(ServerStatus record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.server_status.
     *
     * @mbggenerated
     */
    Cursor<ServerStatus> cursorByExample(ServerStatusExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.server_status.
     *
     * @mbggenerated
     */
    List<List<ServerStatus>> selectPksByExample(ServerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    List<ServerStatus> selectByExample(ServerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    ServerStatus selectByPrimaryKey(String statusCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    int updateByExampleSelective(@Param("record") ServerStatus record, @Param("example") ServerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    int updateByExample(@Param("record") ServerStatus record, @Param("example") ServerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    int updateByPrimaryKeySelective(ServerStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.server_status
     *
     * @mbg.generated Wed Mar 29 11:58:10 KST 2023
     */
    int updateByPrimaryKey(ServerStatus record);
}