package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.SocialAuthentication;
import java.util.List;
import com.ocko.aventador.dao.model.aventador.SocialAuthenticationExample;
import org.apache.ibatis.annotations.Param;

public interface SocialAuthenticationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	long countByExample(SocialAuthenticationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	int deleteByExample(SocialAuthenticationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	int insert(SocialAuthentication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	int insertSelective(SocialAuthentication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	List<SocialAuthentication> selectByExample(SocialAuthenticationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	SocialAuthentication selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	int updateByExampleSelective(@Param("record") SocialAuthentication record,
			@Param("example") SocialAuthenticationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	int updateByExample(@Param("record") SocialAuthentication record,
			@Param("example") SocialAuthenticationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	int updateByPrimaryKeySelective(SocialAuthentication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.social_authentication
	 * @mbg.generated  Fri Nov 19 23:46:31 KST 2021
	 */
	int updateByPrimaryKey(SocialAuthentication record);
}