package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.ViewInfiniteIncome;
import com.ocko.aventador.dao.model.aventador.ViewInfiniteIncomeExample;
import com.ocko.aventador.model.infinite.IncomeByMonthly;
import com.ocko.aventador.model.infinite.IncomeByStock;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface ViewInfiniteIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    long countByExample(ViewInfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_income.
     * 
     * @mbggenerated
     */
    void truncate();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    int deleteByExample(ViewInfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_income.
     *
     * @mbggenerated
     */
    int insertIgnore(ViewInfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_income.
     *
     * @mbggenerated
     */
    int upsert(ViewInfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    int insert(ViewInfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    int insertSelective(ViewInfiniteIncome record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_income.
     *
     * @mbggenerated
     */
    Cursor<ViewInfiniteIncome> cursorByExample(ViewInfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_income.
     *
     * @mbggenerated
     */
    List<List<ViewInfiniteIncome>> selectPksByExample(ViewInfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    List<ViewInfiniteIncome> selectByExample(ViewInfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    int updateByExampleSelective(@Param("record") ViewInfiniteIncome record, @Param("example") ViewInfiniteIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_income
     *
     * @mbg.generated Wed Apr 13 14:25:10 KST 2022
     */
    int updateByExample(@Param("record") ViewInfiniteIncome record, @Param("example") ViewInfiniteIncomeExample example);

	/**
	 * @param param
	 * @return
	 */
	List<IncomeByStock> selectIncomeByStock(Map<String, Object> param);

	/**
	 * @param param
	 * @return
	 */
	List<IncomeByMonthly> selectIncomeByMonthly(Map<String, Object> param);
}