package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.ViewInfiniteBuyTwoMonth;
import com.ocko.aventador.dao.model.aventador.ViewInfiniteBuyTwoMonthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface ViewInfiniteBuyTwoMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month
     *
     * @mbg.generated Thu Dec 16 18:26:46 KST 2021
     */
    long countByExample(ViewInfiniteBuyTwoMonthExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month.
     * 
     * @mbggenerated
     */
    void truncate();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month
     *
     * @mbg.generated Thu Dec 16 18:26:46 KST 2021
     */
    int deleteByExample(ViewInfiniteBuyTwoMonthExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month.
     *
     * @mbggenerated
     */
    int insertIgnore(ViewInfiniteBuyTwoMonth record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month.
     *
     * @mbggenerated
     */
    int upsert(ViewInfiniteBuyTwoMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month
     *
     * @mbg.generated Thu Dec 16 18:26:46 KST 2021
     */
    int insert(ViewInfiniteBuyTwoMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month
     *
     * @mbg.generated Thu Dec 16 18:26:46 KST 2021
     */
    int insertSelective(ViewInfiniteBuyTwoMonth record);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month.
     *
     * @mbggenerated
     */
    Cursor<ViewInfiniteBuyTwoMonth> cursorByExample(ViewInfiniteBuyTwoMonthExample example);

    /**
     * This method was generated by MyBatis Generator Soov Plugins.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month.
     *
     * @mbggenerated
     */
    List<List<ViewInfiniteBuyTwoMonth>> selectPksByExample(ViewInfiniteBuyTwoMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month
     *
     * @mbg.generated Thu Dec 16 18:26:46 KST 2021
     */
    List<ViewInfiniteBuyTwoMonth> selectByExample(ViewInfiniteBuyTwoMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month
     *
     * @mbg.generated Thu Dec 16 18:26:46 KST 2021
     */
    int updateByExampleSelective(@Param("record") ViewInfiniteBuyTwoMonth record, @Param("example") ViewInfiniteBuyTwoMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aventador.view_infinite_buy_two_month
     *
     * @mbg.generated Thu Dec 16 18:26:46 KST 2021
     */
    int updateByExample(@Param("record") ViewInfiniteBuyTwoMonth record, @Param("example") ViewInfiniteBuyTwoMonthExample example);
}