package com.ocko.aventador.dao.persistence.aventador;

import com.ocko.aventador.dao.model.aventador.ViewTodayStock;
import com.ocko.aventador.dao.model.aventador.ViewTodayStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

public interface ViewTodayStockMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.view_today_stock
	 * @mbg.generated  Thu Nov 25 22:33:06 KST 2021
	 */
	long countByExample(ViewTodayStockExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.view_today_stock.
	 * @mbggenerated
	 */
	void truncate();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.view_today_stock
	 * @mbg.generated  Thu Nov 25 22:33:06 KST 2021
	 */
	int deleteByExample(ViewTodayStockExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.view_today_stock.
	 * @mbggenerated
	 */
	int insertIgnore(ViewTodayStock record);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.view_today_stock.
	 * @mbggenerated
	 */
	int upsert(ViewTodayStock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.view_today_stock
	 * @mbg.generated  Thu Nov 25 22:33:06 KST 2021
	 */
	int insert(ViewTodayStock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.view_today_stock
	 * @mbg.generated  Thu Nov 25 22:33:06 KST 2021
	 */
	int insertSelective(ViewTodayStock record);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.view_today_stock.
	 * @mbggenerated
	 */
	Cursor<ViewTodayStock> cursorByExample(ViewTodayStockExample example);

	/**
	 * This method was generated by MyBatis Generator Soov Plugins. This method corresponds to the database table aventador.view_today_stock.
	 * @mbggenerated
	 */
	List<List<ViewTodayStock>> selectPksByExample(ViewTodayStockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.view_today_stock
	 * @mbg.generated  Thu Nov 25 22:33:06 KST 2021
	 */
	List<ViewTodayStock> selectByExample(ViewTodayStockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.view_today_stock
	 * @mbg.generated  Thu Nov 25 22:33:06 KST 2021
	 */
	int updateByExampleSelective(@Param("record") ViewTodayStock record,
			@Param("example") ViewTodayStockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table aventador.view_today_stock
	 * @mbg.generated  Thu Nov 25 22:33:06 KST 2021
	 */
	int updateByExample(@Param("record") ViewTodayStock record, @Param("example") ViewTodayStockExample example);
}