spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    enabled: true
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aventador
    username: aventador
    password: aventadorU$3r
  custom:
    basePackage: com.ocko.aventador
  security:
    oauth2:
      client:
        registration:
          NAVER:
            client-id: 7mHREwNLi4YvnhixgB82
            client-secret: lbPzJXzVg1
server:
  servlet:
    context-path: /aventador
  port: 8088