spring:
  profiles:
    active: @activatedProperties@
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    enabled: true
    cache: false
  datasource:
    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 12
      connection-timeout: 300000
      minimum-idle: 2
      data-source-properties: 
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  custom:
    basePackage: com.ocko.aventador
  security:
    oauth2:
      client:
        registration:
          NAVER:
            client-id: ENC(zef6d42pOBR9Hna6Niz6QKGO2B2jDB4vaej9ZE9CPjk=)
            client-secret: ENC(cYSwqcs3oDMVJsG6ZKNZ2NR+o74LexKR)
            
---
spring:
  profiles: master
  datasource:
    driver-class-name: ENC(ye9Lw58nw2l4xSWUyb1wnM3L6PEt/HdXx7EnNNnVVH8=)
    url: ENC(CHyp2LGScwzoiTTSqloq0JaLiSHLDUQDuEO6lXVTqkk8iCKYM4QMnJ5+eakvAw+OcghOqrOzIqa2x7RHZ9FU+vOgTDnSQeg+bgNkCOxkXYE=)
    username: ENC(RUroYQGGIPimhvDFEcogEcxj1x6/VoI8)
    password: ENC(s6AoT4xvNOr4qSkft6rJzuXRIDqXpA/2)
    
server:
  servlet:
    context-path: /
  port: 8088
  
---
spring:
  profiles: dev
  datasource:
    driver-class-name: ENC(ye9Lw58nw2l4xSWUyb1wnM3L6PEt/HdXx7EnNNnVVH8=)
    url: ENC(ubYshY/ffidSYQD1r+irNL7FjutCEvgLm18zm5JD3eJ0+d5bk0ie9cOhjuVPw8uQW0UqgMDr9pVbcg48nh081oJmssCF6nJmX6Y0thtUXgk=)
    username: ENC(VCsTBvmEoo2IHyT1+UHjID4rcnitRTnd)
    password: ENC(jwpF9fVuBlKXdhYzxLugddt/l4zY3nZX)
            
server:
  servlet:
    context-path: /dev
  port: 8088