spring:
  profiles:
    active: @activatedProperties@
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    enabled: true
    cache: false
  datasource:
    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 12
      connection-timeout: 300000
      minimum-idle: 2
      data-source-properties: 
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  custom:
    basePackage: com.ocko.aventador
  security:
    oauth2:
      client:
        registration:
          NAVER:
            client-id: QyziMDfXfgFrKsHmyHIs
            client-secret: ZUgzqbmb_v
            
---
spring:
  profiles: master
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ocko.co.kr:5432/aventador?stringtype=unspecified
    username: aventador
    password: aventadorU$3r
    
server:
  servlet:
    context-path: /
  port: 8088
  
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ocko.co.kr:5432/aventador_dev?stringtype=unspecified
    username: aventadordev
    password: aventadorDevU$3r
    
server:
  servlet:
    context-path: /dev
  port: 8088